DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS deadline;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(30) UNIQUE NOT NULL,
  password VARCHAR(30) NOT NULL,
  verified BIT,
  ver_code INTEGER
);

CREATE TABLE deadline (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(30) NOT NULL,
  time DATETIME NOT NULL,
  from_bb BIT,
  set_reminder BIT,
  user_id INTEGER,
  FOREIGN KEY (user_id) REFERENCES user (id)
);